# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactface',
            name='message',
            field=models.TextField(default='-', max_length=2000),
        ),
    ]
