# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_contactface_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbiesAndInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(max_length=120)),
            ],
        ),
    ]
