# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0005_auto_20170829_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactface',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
