# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0006_auto_20170830_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactface',
            name='message',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
